# Generated by Django 5.2.17 on 2026-09-28 19:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('push', 'Push'), ('pull', 'Pull'), ('run', 'Run'), ('core', 'Core'), ('skill', 'Skill')], max_length=20)),
                ('target_muscles', models.ManyToManyField(blank=True, related_name='exercises', to='workouts.muscle')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('volume', 'Volume Training'), ('strength', 'Strength Training'), ('explosive', 'Explosive Power'), ('record', 'Record Training'), ('recovery', 'Recovery Training'), ('endurance', 'Endurance Training')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Lbs', max_digits=5, null=True)),
                ('duration', models.DurationField(blank=True, help_text='Exercise duration (e.g., 00:01:30)', null=True)),
                ('rest_time', models.DurationField(default=datetime.timedelta(seconds=60), help_text='Rest time after a set (e.g., 00:01:30 or 90 seconds)')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sets', to='workouts.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.workout')),
            ],
        ),
    ]
